name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test (OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}})
    strategy:
      matrix:
        elixir: ['1.10', '1.9', '1.8', '1.7', '1.6.6']
        # All of the above can use this version. For details see: https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
        otp: [21]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test

  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 21
          elixir-version: '1.10'
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix credo --strict

      - name: Restore Dialyzer Cache
        uses: actions/download-artifact@v1
        with:
          name: PLT Cache
          path: priv/plts

      - run: mix dialyzer --halt-exit-status

      - name: Upload Dialyzer Cache
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: PLT Cache
          path: priv/plts